config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "home", to: "homes#home"
  get "about", to: "homes#about"

  get "event", to: "events#event"
  get "detal/:id", to: "events#detal"
  post "coment", to: "events#detal" 
  get "join/:id", to: "events#join"

  get "singup", to: "users#new"
  patch "user/:id/update", to: "users#update"
  post "singup", to: "users#create"
  get "mypage", to: "users#mypage"
  get "user/:id/edit", to: "users#edit"
  get "notjoin/:id", to: "users#notjoin"
  
  get "login", to: "sessions#login"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"

  post "post", to: "posts#create"
  get "post", to: "posts#show"
  get "posted/edit/:id", to: "posts#edit"
  post "posted/:id/update", to: "posts#update"
  delete "posted/destroy/:id", to: "posts#destroy"

  
end

app/models/user.rb
class User < ApplicationRecord
    # before_save { self.email = email.downcase }
  
    has_many :coments
    has_many :joins
    validates :name, presence: true, length: {maximum: 20}
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: {maximum: 50},format: { with: VALID_EMAIL_REGEX },uniqueness: { case_sensitive: false }
    validates :password, presence: true, length: {minimum: 6}, allow_nil:true
    validates :password, presence: true, length: {maximum: 15},  allow_nil:true
    has_secure_password    

    mount_uploader :img, ImgUploader

    def img_size
        if img.size > 5.megabytes
          errors.add(:img, "should be less than 5MB")
        end
      end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # before_action :log_in, only:[:edit, :update, :mypage, :destroy] ログインしてなくても観覧できるようになっている

    def new
        @user = User.new
    end

    def create
         @user = User.new(user_params) #このコードは @user = User.new(naem: name, email:email, password: password, password_confirmation:pasword_confirtion)と同じ
         
        # @user = User.new(name: name, email: email, password: password, password_confirmation: password_confirmation)
        if @user.save
            flash[:success] = "登録が完了しました"
            redirect_to ("/login")
        else
            render "new"
        end
    end

    def mypage
        @user = User.find_by(id: session[:user_id])
        user_id = session[:user_id]
        # joinedEvent = Join.where(user_id: session[:user_id]).all
        @joins = Post.joins(:joins).select("posts.*, joins.user_id, joins.post_id").where(joins: {user_id: user_id})
        
    end

    def notjoin
        post_id = params[:id]
        Join.find_by(post_id: post_id).delete
        redirect_to "/mypage"
    end

    def edit
        user_id = params[:id].to_i
        id = session[:user_id]
       
        if user_id == id
           @user = User.find_by(id: params[:id])
        else
            flash[:notice] = "ログインしてくだい"
            redirect_to ('/login')
        end
    end

    def update
        @user = User.find_by(id: params[:id])
        if @user.update(user_params)
            flash[:notice] = "変更しました"
            redirect_to "/mypage"
        else
            flash[:notice] = "エラーです"
            render "mypage"
        end
    end

        private
        def user_params
            params.require(:user).permit(:name, :email, :password,:password_confirmation, :img, :intro)
        end

        def loginuser

        end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="user-edit">
<div class="edit-form">
<h1>プロフィール編集</h1>
<%= form_with model: @user, url: "/user/#{@user.id}/update" do |f| %>
    <div class="u-e">
      <p><%= f.label :name %>
      <%= f.text_field :name, class: "u-e-n" %> </p>
      
      <p><%= f.label :email %>
      <%= f.text_field :email, class: "u-e-e" %></p>

      <p><%= f.label :Self_introduction %>
      <%= f.text_area :intro, class: "u-e-i" %></p>

      <p><%= f.label :img %>
      <%= f.file_field :img %></p>

     
      <%= f.submit "プロフィール編集", class: "u-e-s" %>
    
     </div>
  <% end %>
</div>
</div>

app/views/users/login.html.erb
<div class="login">
    <h1>ログイン</h1>
    <div class="login-form">
        <%= form_for() %>
    </div>
</div>

app/views/users/mypage.html.erb
<div class="mypageAll">
<% if @user %>

<div class="profile">
   <div class="p-in">
    <% if @user.img.url != nil  %>
      <%= image_tag @user.img.url %>
    <% else %>
      <%= image_tag("city.png") %>
    <% end %>
    <p class="user-name"><%= @user.name %></p>
    <p class="user-intro"><%= @user.intro %></p>
    <span class="p-user-edit"><%= link_to "プロフィール編集", "/user/#{@user.id}/edit" %></span>
   </div>
</div>
    
<% if @joins[0] != nil %>
<div class="joined-all">
 <% @joins.each do |join| %>
 <div class="jo">
  <ul>
     <% if join.img.url != nil %>
       <li class="joined-img"><%= image_tag join.img.url %></li>
     <% else %>
       <li class="joined-img"><%= image_tag("will.png") %></li>
    <% end %>
     <li class="joined-title"><%= join.title %></li>
     <li class="joined-date">開催日:<%= join.date %></li>
     <li class="joined-content"><%= join.content %></li>
     <li class="joined-not"><%= link_to "参加取り消し", "/notjoin/#{join.post_id}" %></li>
      
     <li class="joined-link"><%= link_to "詳細", "/detal/#{join.post_id}" %></li>

  </ul>
  </div>
 <% end %>
<% else %>
<div class="Notjoin">
  <p>参加しているイベントはありません。<br>イベント一覧からイベントに参加しましょう</p>
  <%= link_to "イベント一覧", "/event" %>
</div>
<% end %>
</div>
<%# </div> %>
<% else %>
    <h1>ログインしてください</h1>
<% end %>

</div>

app/views/users/new.html.erb
<div class="singup">
    <h1>新規登録</h1>
    <div class="singup-form">
        <%= form_for(@user, url: singup_path) do |f| %>
         <%= render 'shared/error_messages' %>
         <div class="form">
        <p><%= f.label :name %>
        <%= f.text_field :name %></p>

        <p><%= f.label :email %>
        <%= f.email_field :email %></p>

        <p><%= f.label :password %>
        <%= f.password_field :password %></p>

        <p><%= f.label :password_confirmation, "Confirmation" %>
        <%= f.password_field :password_confirmation %></p>

        <p><%= f.label :Self_introduction %>
          <%= f.text_area :intro ,placeholder: "自己紹介文:右下から拡大できます",:size => "50*70"%></p>

        <p><%= f.label  :img %>
        <%= f.file_field :img %></p>
        

        <p><%= f.submit "新規登録", class: "btn btn-primary" %></p>
        <% end %> 
        </div>
    </div>
</div>