config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "home", to: "homes#home"
  get "about", to: "homes#about"

  get "event", to: "events#event"
  get "detal/:id", to: "events#detal"
  post "coment", to: "events#detal" 
  get "join/:id", to: "events#join"

  get "singup", to: "users#new"
  patch "user/:id/update", to: "users#update"
  post "singup", to: "users#create"
  get "mypage", to: "users#mypage"
  get "user/:id/edit", to: "users#edit"
  get "notjoin/:id", to: "users#notjoin"
  
  get "login", to: "sessions#login"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"

  post "post", to: "posts#create"
  get "post", to: "posts#show"
  get "posted/edit/:id", to: "posts#edit"
  post "posted/:id/update", to: "posts#update"
  delete "posted/destroy/:id", to: "posts#destroy"

  
end

app/models/event.rb
class Event < ApplicationRecord
    validates :coment, presence: true, length: {minimum: 1}
    validates :user_id, presence: true
    validates :posted_id, presence: true
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    def event 
        @user = User.find_by(id: session[:user_id])
        @posts = Post.all
        
        # @posts = Post.page(params[:page]).per(20)
        @posts = Kaminari.paginate_array(@posts).page(params[:page]).per(5)

        Coment.new
        Join.new
        user_id = session[:user_id]
        @joinedEvent = Join.where(user_id: session[:user_id]).all
        @joins = Post.joins(:joins).select("posts.*, joins.*").where(joins: {user_id: user_id})

        # 参加しているかどうか
        joinId = {}
        @joinedEvent.each do |u|
          joinId[u.post_id] = u.post_id
        end
        joinId
        @joinId = joinId.values
        
        
    end

    def detal
        #コメントの保存
        @user = session[:user_id]
        if params[:id] != nil
          @posted_id = params[:id]
        else
          @posted_id = params[:posted_id]
        end
        user_id = session[:user_id]
        if params[:coment] != nil
          coment = params[:coment]
          comentsub = Coment.new(coment: coment, user_id: user_id, post_id: @posted_id)
          if comentsub.save
            flash[:notice] = "コメントしました"
            redirect_to ("/detal/#{@posted_id}")
          else
            flash[:notice] = "エラー"
            redirect_to ("/detal/#{@posted_id}")
          end
        end
        
        posted_id = @posted_id
        #詳細ページのコメント
        @coments = User.joins(:coments).select("users.name, users.id, users.img, coments.coment, coments.created_at").all.where(coments: {post_id: posted_id}).order('coments.created_at desc')
        
        
        # 詳細ページの右側
        @posteds = Post.find_by(id: @posted_id)

        # 参加人数の表示
        @num = Join.where(post_id: @posted_id).count

        # 参加しているかどうか
        @join = Join.where(post_id: posted_id).where(user_id: session[:user_id]).first
        
        
    end

    def join

      user_id = session[:user_id]
      posted_id = params[:id]
      join = Join.new(user_id: user_id, post_id: posted_id)
      if join.save
        flash[:notice] = "参加登録完了しました"
        redirect_to "/mypage"
      else
        flash[:notice] = "参加できませんでした"
        redirect_to "/event"
      end


    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/detal.html.erb
<div class="detal-all">
    <div class="detal">
    <% if @user %>
        <div class="detal-coment-post">
            <%= form_with model: @event, url: coment_path do |f| %>
             <p><%= f.label :coment %>
                <%= f.text_field :coment %></p>
            
            <p><%= f.hidden_field :posted_id, :value => @posted_id %></p>
             <p><%= f.submit "投稿" %></p>
            <% end %>

        
        </div>

    <div class="detal-coment-result">
      <% @coments.each do |coment| %>
      <% if @user == coment.id %>
        <div class="mycoment">
      <% else %>
        <div class="coment">
      <% end %>

        <ul>
           
           <% if coment.img.url != nil %>
           <% if @user == coment.id %>
            <li class="d-c-myimg"><%= image_tag coment.img.url %></li> 
             <% else %>
            <li class="d-c-img"><%= image_tag coment.img.url %></li> 

            <% end %>
          <% else %>
            <% if @user == coment.id %>
              <li class="d-c-myimg"> <%= image_tag("will.png") %></li> 
            <% else %>
              <li class="d-c-img"> <%= image_tag("will.png") %></li> 
            <% end %>
           <% end %>
            <% if @user == coment.id %>
              <li class="d-c-myname">：<%= coment.name %></li>
            <% else %>
              <li class="d-c-name"><%= coment.name %>：</li>
           <% end %>
           <% if @user == coment.id %>
              <li class="d-c-mytime"><%= coment.created_at.strftime('%m/%d %H:%M') %></li>
           <% else %>
              <li class="d-c-time"><%= coment.created_at.strftime('%m/%d %H:%M') %></li>
           <% end %>
           
        </ul>
        <% if @user == coment.id %>
            <p class="d-c-mycome"><%= coment.coment %></p>
        <% else %>
            <p class="d-c-come"><%= coment.coment %></p>
        <% end %>
        </div>
      <% end %>
    </div>
    <% else %>
    <div class="detal-not">
    <p>新規登録するとコメントが観覧できます</p>
    </div>
    <% end %>
    </div>


    <div class="detal">
      <div class="detal-posted">
        <% if @posteds.img.url != nil %>
            <%= image_tag @posteds.img.url %>
        <% else %>
            <%= image_tag("will.png") %>
        <% end %>
        <p class="detal-title"><%=  @posteds.title %></p>
        <p class="detal-num">現在参加人数:<%= @num %>人</p>
        <% if @join != nil %>
        <p class="detal-joined">『参加済』</p>
      <% else %>
        <p class="detal-join"><%= link_to "参加する", "/join/#{@posted_id}" %></p>
      <% end %>
        <p class="detal-date">開催日  <%=  @posteds.date %></p>
        <p class="detal-content"><%=  @posteds.content %></p>
      </div>
    </div>






</div>

app/views/events/event.erb
<%if @user %>

<div class="event">
<div class="event-one event-co">
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>cot</h1>

</div>


<div class="event-co">
 <% @posts.each do |post| %>
 <div class="posted">
  <ul>
     <% if post.img? %>
       <li class="posted-img"><%= image_tag post.img.url %></li>
     <% else %>
       <li class="posted-img"><%= image_tag("city.png") %></li>
    <% end %>
     <li class="posted-title"><%= post.title %></li>
     <li class="posted-date">開催日:<%= post.date %></li>
     <li class="posted-content"><%= post.content %></li>
     <li class="post-detal"><%=link_to "詳細", "/detal/#{post.id}" %></li>
  </ul>
  </div>
 <% end %>

</div>
</div>

<%else%>
<p>ログインしてください</p>
<% end %>

app/views/events/event.html.erb
<%if @user %>

<%# <div class="event">
<div class="event-one event-co">
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>content</h1>
<h1>cot</h1>

</div> %>
<%# kaminari 使い方検索 ページねいとの仕方 %>

<div class="event-co">
 <% @posts.each do |post| %>
 <div class="posted fadein">
  <ul>
     <% if post.img? %>
       <li class="posted-img"><%= image_tag post.img.url %></li>
     <% else %>
       <li class="posted-img"><%= image_tag("will.png") %></li>
    <% end %>
     <li class="posted-title"><%= post.title %></li>
     <li class="posted-date">開催日:<%= post.date %></li>
     <li class="posted-content"><%= post.content %></li>
     <% if @user.admin == 1 %>
       <li class="posted-destroy"><%= link_to '削除', "/posted/destroy/#{post.id}", method: :delete, data: { confirm: "You sure?" } %></li>
       <li class="posted-update"><%= link_to "編集", "/posted/edit/#{post.id}" %></li>
      <% end %>

      
      <% if @joinId.any? { |w| w == post.id }%>
        <li class="posted-joined">『参加済』</li>
      <% else %>
        <li class="posted-join"><%= link_to "参加する", "/join/#{post.id}" %></li>
      <% end %>

      
     <li class="posted-link"><%= link_to "詳細", "/detal/#{post.id}" %></li>
  </ul>
  </div>
 <% end %>
<%= paginate @posts %>
</div>
</div>

<%else%>
<div class="event-co">
 <% @posts.each do |post| %>
 <div class="posted">
  <ul>
     <% if post.img? %>
       <li class="posted-img"><%= image_tag post.img.url %></li>
     <% else %>
       <li class="posted-img"><%= image_tag("will.png") %></li>
    <% end %>
     <li class="posted-title"><%= post.title %></li>
     <li class="posted-date">開催日:<%= post.date %></li>
     <li class="posted-content"><%= post.content %></li>
     <li class="posted-link"><%= link_to "詳細", "/detal/#{post.id}" %></li>
  </ul>
  </div>
 <% end %>

</div>
</div>
<% end %>