config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "home", to: "homes#home"
  get "about", to: "homes#about"

  get "event", to: "events#event"
  get "detal/:id", to: "events#detal"
  post "coment", to: "events#detal" 
  get "join/:id", to: "events#join"

  get "singup", to: "users#new"
  patch "user/:id/update", to: "users#update"
  post "singup", to: "users#create"
  get "mypage", to: "users#mypage"
  get "user/:id/edit", to: "users#edit"
  get "notjoin/:id", to: "users#notjoin"
  
  get "login", to: "sessions#login"
  post "login", to: "sessions#create"
  get "logout", to: "sessions#destroy"

  post "post", to: "posts#create"
  get "post", to: "posts#show"
  get "posted/edit/:id", to: "posts#edit"
  post "posted/:id/update", to: "posts#update"
  delete "posted/destroy/:id", to: "posts#destroy"

  
end

app/models/post.rb
class Post < ApplicationRecord
    validates :title, presence: true
    validates :content, presence: true
    mount_uploader :img, ImgUploader
    # belongs_to :user
    has_many :coments, dependent: :destroy
    has_many :joins, dependent: :destroy
    default_scope -> { order(created_at: :desc) }
    # validate :img_size  サイズの確認するGEMファイルが必要説

    private
     # アップロードされた画像のサイズをバリデーションする
  def img_size
    if img.size > 5.megabytes
      errors.add(:img, "should be less than 5MB")
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :post_params, only:[:create]
    def show

        
        @user = User.find_by(id: session[:user_id])
        
        if session[:user_id] == nil
            flash[:notice] = "権限がありません"
            redirect_to "/login"
        else
            if  @user.admin == nil 
                flash[:notice] = "権限がありません"
                redirect_to "/login"
            else
                @post = Post.new
                render 'post'
            end
        end
    end

    def create
        
        user_id = session[:user_id]
        title = params[:post][:title]
        content = params[:post][:content]
        date = params[:post][:date]
        img = params[:post][:img]
        @post = Post.new(title: title, content: content,user_id: user_id, date: date, img: img)
    
        if @post.save
            # redirect_to "events"
            redirect_to "/event"
        else 

            render "post"
            flash[:notice] = "error"
        end
    end

    def destroy
        posted_id = params[:id]
        posted = Post.find_by(id: posted_id)
        posted.destroy
    
        redirect_to "/event"
      end
  
      def edit
        user = User.find_by(id: session[:user_id])
 
        if user != nil && user.admin == 1
            posted_id = params[:id]
            @posted = Post.find_by(id: posted_id)
            render :edit
        else    
            flash[:notice] = "権限がありません"
            redirect_to "/login"
        end
      end
  
      def update
        posted_id = params[:id]
        @posted = Post.find_by(id: posted_id)
        title = params[:title]
        date = params[:date]
        content = params[:content]
        img = params[:img]
        if @posted.update(title: title, date: date, content: content, img: img)
            flash[:notice] = "編集しました"
            redirect_to "/event"
        else
            flash[:notice] = "エラーです"
            redirect_to "/event"
        end
        
        
      end

      private
      def post_params
        params.require(:post).permit(:title, :content, :date, :img)
      end

      
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/edit.html.erb
<div class="poated-edit-all"></div>
<div class="all">
<div class="edit-title">
  <h1>投稿編集</h1>
</div>
<div class="e-post-form">
    <%= form_with model: @post, url:"/posted/#{@posted.id}/update" do |f|  %>
        <div class="posted-edit">
            <p><%= f.label :title %>
               <%= f.text_field :title, value: "#{@posted.title}" %></p>

            <p><%= f.label :date %>
              <%= f.date_field :date, value: "#{@posted.date}" %></p>

            <p><%= f.label :content %>
              <%= f.text_area :content, value: "#{@posted.content}" %></p>

              <p><%= f.label :img %>
                <%= f.file_field :img %></p>


            <p><%= f.submit "編集", class: "btn btn-primary" %></p>

        
        </div>


    <% end %>

</div>
</div>

app/views/posts/post.html.erb
<div class="post-all">
<div class="all">
<div class="title">
  <h1>イベント投稿</h1>
</div>

<div class="e-post-form">
    <%= form_with model: @post, url: post_path do |f| %>
     
    
      <div class="post">
        <p><%= f.label :title %>
        <%= f.text_field :title %></p>

        <p><%= f.label :date %>
        <%= f.date_field :date %></p>
        
        <p><%= f.label :content %>
        <%= f.text_area  :content, placeholder: "本文を入力してください", :size => "70*40" %></p> <%# 本文の縦と横の長さの調整 %>
        

        <p><%= f.label  :img %>
        <%= f.file_field :img %></p>

        <p><%= f.submit "投稿", class: "btn btn-primary" %></p>
      </div>
    <% end %>
</div>
</div>
</div>